### ISSUE TITLE
Roll on/off a button

### ISSUE THREAD

**Issue by budda** [Flaxis/slick-ui#1]
Can you add the ability to drag finger / mouse off and back on to a selected button in case user decides they don't want to click / cancel their action 

Congrats on the Slick project. You had more time that me to get this thing out there! I look forward to using it.

**Comment by Flaxis** [comment]
Thanks for your interest and feedback :)
The feature you suggested has been added and released as 0.1.5

**Comment by budda** [comment]
Wow fast turn around! 👍

**Comment by Flaxis** [comment]
No problem ;)
