### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by 7yl4r** [Flaxis/slick-ui#11]
Firstly, this is really nice work and thank you for making it open source regardless of your license choice.

I'm a bit wary of using something that doesn't include a license. Phaser is licensed under the very permissive MIT license --- which I would be happy to see here too, but the choice is yours of course.

**Comment by Flaxis** [comment]
I really don't mind what you do with this library, so let's just say it's released as public domain :)

**Comment by Flaxis** [comment]
I should add that it only applies to the library itself of course. Phaser and the Kenney assets still have their own licenses which should be followed.

**Comment by 7yl4r** [comment]
That's great! I'm definitely going to use this then. The look fits in perfectly with a little game I'm making, and I'd like to find a better way to code for menus in phaser. Thanks!

As a note for anyone else coming by : Kenny's assets used here are [ui-pack](http://kenney.nl/assets/ui-pack) ( [CC0](https://tldrlegal.com/license/creative-commons-cc0-1.0-universal) public domain license). 

@Flaxis : If you like you could add a section in the readme or add the CC0 license to the repo so it will be easier for others to see that they can use it freely.

**Comment by Flaxis** [comment]
Cool! For those who want to customize the theming even more, you can create [custom 'renderers'](https://github.com/Flaxis/slick-ui/tree/master/src/Element/Renderer) and specify them in the [theme json file](https://github.com/Flaxis/slick-ui/blob/master/preview/assets/ui/kenney/kenney.json#L19).
Also, updated the readme with the information about legal stuff :)
