### ISSUE TITLE
Vertical Slider (new Feature)

### ISSUE THREAD

**Issue by ldd** [Flaxis/slick-ui#13]
I love this plugin already, but for my purposes I needed a Vertical Slider. It is not really hard to do, and it is a really simple way of adding more features. My dirty way of doing it was:

1) copy `SliderRenderer.js,` ```Slider.js```
2) alter the code to use `y` and `height` instead of `x` and `width`

I would love to have a vertical slider added for the next release, and I simply propose a new parameter when calling `VSlider` so that instead of doing
        `var slider = new SlickUI.Element.Slider(16,100, someSize, someValue);`

You do 
        `var slider = new SlickUI.Element.Slider(16,100, someSize, someValue, "vertical");` or
        `var slider = new SlickUI.Element.Slider(16,100, someSize, someValue, "horizontal");` 

All that is required is to change a couple of lines in `Slider.js` (this is very straightforward), and to add `VSliderRenderer` ( I had lots of trouble with that part so I just didn't display anything fancy with it for the vertical slider)

**Comment by Flaxis** [comment]
Sounds like a great idea. I've [implemented this](http://slick-ui.com/preview/slider.html) straight away.
I haven't tagged a release for it yet. You can however use dev-master to start using the code I just wrote. Or do you want me to tag it so you can update it using Bower?

**Comment by ldd** [comment]
Wow, that was fast. I was working on a potential pull request that basically did everything you did [here](https://gist.github.com/ldd/3d5e4669eea6098bc4cf8d594a051a35). 

Anyways, I don't need a tagged release, but it would probably be a good idea to add it.

**Comment by Flaxis** [comment]
Ah, well, apologies for interrupting your work then :p You can use the repository version now anyway :)

I agree tagging would be a good idea, I'll do it at some point in the near future, but also remove some older tags, because I don't want to support them all.
