### ISSUE TITLE
how to hide/delete panels / elements?

### ISSUE THREAD

**Issue by ilackarms** [Flaxis/slick-ui#15]
Hey, sorry if this is a dumb question...

I'm not sure how to delete elements (say, hide/show additional menus). Is there a builtin way to do this, or should I directly show/hide the sprites associated with each element?

**Comment by Flaxis** [comment]
Most elements have a setter on them called 'visible' which corresponds to their associated displaygroup, but looking through my code I see now this isn't the case for every element. I should probably add them when I have the time.

**Comment by Flaxis** [comment]
I've added some setters in 4d0bbe1738f29bc483f216f7bb03e03fb4914b58 and bb3007e0ac892a950a5b43da77954307d0222ed9
Have a nice day!
