### ISSUE TITLE
Text Inputs? 

### ISSUE THREAD

**Issue by devmattrick** [Flaxis/slick-ui#2]
I've just recently found this project and I can already see it being super useful. A major thing that is currently missing from this is text input. The only way I know to accept text input on Phaser is to make a "hack" using the HTML <input> element, but something that uses the canvas natively would be extremely helpful.

**Comment by Flaxis** [comment]
Good point. I've been thinking about introducing text inputs before. For mobile users, we'd probably have to use an in-canvas virtual keyboard, though, because the native keyboard can't be triggered without the use of HTML. And this of course gives us limitations in the game's minimum width :) But maybe that isn't that big of a problem.

I'll look into it anyway. If you have any suggestions let me know or try setting something up.

**Comment by devmattrick** [comment]
Yeah, unfortunately the only way I know of to open the soft keyboard involves invisible HTML inputs, which would probably not be the best idea. 

Even if it's a PC-only feature, I can still see if being quite useful. I'm not too sure how difficult it would be to create your own soft keyboard for mobile devices. Thanks for the quick reply! :)

**Comment by giorgiobeggiora** [comment]
are you implementing alla the <form> elements? I mean <select>, <textarea>, <input type="file">, <button>, ecc

Thanks.

**Comment by Flaxis** [comment]
Currently working out a text input solution for mobile and desktop users. File input fields will not be supported, because that does not belong in game UI in my opinion.

**Comment by giorgiobeggiora** [comment]
True, the main focus of Phaser is gaming, although sometime Phaser could be used to develop applications.

What about < select > ?

thanks

**Comment by Flaxis** [comment]
This plugin will only facilitate game development UI :)
Please create a new issue addressing dropdown elements and we'll discuss it there.

**Comment by Flaxis** [comment]
The requested feature has been added - text input fields.
Went for a virtual keyboard approach. It might still contain some bugs so use with caution. Also, I will abstract components into several different 'things' in the future (trying to maintain backward compatibility) to allow for more visual independence.

Release 0.3.0

**Comment by devmattrick** [comment]
You are awesome! Thanks so much!
