### ISSUE TITLE
Texture Atlas support

### ISSUE THREAD

**Issue by kwrooijen** [Flaxis/slick-ui#23]
Hey, thanks for your work on this library.

I was wondering if you're planning on adding Texture Atlas support? From what I can tell there doesn't seem to be an option to use an Atlas.

**Comment by Tatwi** [comment]
Atlas support is in the version of SlickUI that I use (latest version). Here is how I do it, 

var coinIcon;
this.cubWindow.add(new SlickUI.Element.DisplayObject(123, this.iconLine + 47, coinIcon = this.game.make.sprite(0, 0, 'atlas')));
coinIcon.frameName = 'ui-coin';

**Comment by kwrooijen** [comment]
All right, thanks! I'll close this ticket then.
