### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by Wargog** [Flaxis/slick-ui#5]
Have you considered writing some Typescript definitions for SlickUI? I am currently using it in my Typescript project but i get a bunch of annoying errors and code completion doesn't work properly.

**Comment by Flaxis** [comment]
I haven't considered it, but since reading your issue I am considering it. I can look into it, but I haven't really worked with Typescript before, so it might take some time

**Comment by JamesSkemp** [comment]
This is closed but I don't see definitions. Am I missing where these are located?

**Comment by RichardSneyd** [comment]
Hi, while this is closed, I have been unable to locate the ts definitions, just wondering have these been created as of yet?

**Comment by ItsGravix** [comment]
@Flaxis 
Where are the definitions? Is this project dead? I really wanted to use SlickUI with my TypeScript game.

**Comment by bradtaniguchi** [comment]
@ItsGravix 
1. There are none
2. Pretty much (last commit over a year ago)
3. You can, you just wont have types. You just need to create your own TS definition file for this library and either expect no "types" for all your imports, or make your own for what you use.
