### ISSUE TITLE
Uncaught TypeError at this.DisplayGroup

### ISSUE THREAD

**Issue by Wargog** [Flaxis/slick-ui#6]
When trying to set `this.displayGroup` to `game.add.group()`, `game` is an undefined reference and throws a TypeError. I've included the log from Chrome on Windows 10 as I'm not sure where this issue is coming from.
[192.168.1.103-1472522944776.txt](https://github.com/Flaxis/slick-ui/files/443869/192.168.1.103-1472522944776.txt)

```
Uncaught TypeError: b is not a constructor
   Phaser v2.6.1 | Pixi.js | WebGL | WebAudio     http://phaser.io ♥♥♥
Tue, 30 Aug 2016 01:59:56 GMT, INFO: Preloading game assets
Tue, 30 Aug 2016 01:59:56 GMT, INFO: Loading Phaser plugins
Tue, 30 Aug 2016 01:59:56 GMT, INFO: Configuring Phaser plugins
Uncaught TypeError: Cannot read property 'group' of undefined
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by Flaxis** [comment]
Strange... I would expect it to complain about the add property in the game object if game is an undefined reference. Could you debug the problem a bit more to find out which line is throwing the exception and what the values of some relevant variables are? It might help to load the source files directly instead of the minified version.

**Comment by Wargog** [comment]
Yea I was going to ask you that, could you include a non-minified version in the dist folder?

**Comment by Flaxis** [comment]
The non-minified version is in the src directory. This exact code is minified using grunt so you should get the same result when simply loading all .js files in the src/*/* directory.

**Comment by Flaxis** [comment]
Is this problem still happening? If not, this issue can be closed. Otherwise I might be able to help out.

**Comment by Wargog** [comment]
Yes it is, even with the latest update from the repo. I haven't had the time to debug and mess with the non-minified version though.
