### ISSUE TITLE
Must have global "game" variable?

### ISSUE THREAD

**Issue by mrmav** [Flaxis/slick-ui#8]
Hi,

I'm getting a reference error:
"slick-ui.min.js:1 Uncaught ReferenceError: game is not defined"

Do I need to have a global game variable? Why?
Thanks

**Comment by eugenemelnikov** [comment]
Have the same when trying to initialize inside create method in game state.

```
var Gm = Gm || {};

Gm.game = new Phaser.Game(200, 200, Phaser.AUTO, 'stage');
Gm.MainMenu.prototype = {
    create: function() {
            var ui = this.game.plugins.add(Phaser.Plugin.SlickUI);
            ui.load('ui/default.json');

            var panel = new SlickUI.Element.Panel(8, 8, this.game.width - 8, this.game.height - 8);
            ui.add(panel);
    }
}
```

**Comment by Flaxis** [comment]
My apologies; at the time of creating the plugin, I didn't cover this situation.
I've pushed a new commit as 0.4.1 which should fix this. Please confirm it's fixed :)

**Comment by eugenemelnikov** [comment]
Thank you. Now i can go with this.game in game states.

Strange, same code as i posted above now produce error on ui.add(panel). Here log from Chrome

```
Uncaught TypeError: Cannot read property 'panel' of null
SlickUI.Element.Panel.init @ slick-ui.min.js:1
SlickUI.Container.Container.add @ slick-ui.min.js:1
Phaser.Plugin.SlickUI.add @ slick-ui.min.js:1
Gm.MainMenu.create @ index.html:69
Phaser.StateManager.loadComplete @ phaser.js:30083
Phaser.StateManager.preUpdate @ phaser.js:29860
Phaser.Game.updateLogic @ phaser.js:36333
Phaser.Game.update @ phaser.js:36280
Phaser.RequestAnimationFrame.updateRAF @ phaser.js:61979
_onLoop @ phaser.js:61962
```

Also i get a warning before this error:

`Phaser.Cache.getJSON: Key "slick-ui-theme" not found in Cache.`

**Comment by shinyvision** [comment]
You have to preload the plugin in every state that uses the plugin. I'm not exactly sure why this is, since Phaser should keep the cache alive throughout states as far as I know. Maybe it behaves differently in plugins...

@jorgenoro is this issue fixed in your situation as well?

**Comment by eugenemelnikov** [comment]
Yes, I do 

```
var ui = this.game.plugins.add(Phaser.Plugin.SlickUI);
ui.load('ui/default.json');
```

in my MainMenu game state. Also i have Boot and Preload states before, but no need to use plugin here.

Will look on this closer today late.

**Comment by mrmav** [comment]
Hey @richard-fizz , 
I've been testing and the global variable issue is fixed for me.
Thanks a lot, and congratulations for such a great plugin!
I'll close the issue.
